# Generated by Django 5.1.4 on 2025-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetsu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donguha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('fav_character', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
